[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
bevy = "0.6.0"
once_cell = "1.10.0"
rand = "0.8.5"

[features]
